### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by mitevpi** [wynged/DynaFire#1]
Where should the files within the "Deploy" folder be placed for this to be installed? Also, once installed, how is this activated from within Dynamo?

**Comment by wynged** [comment]
There are better install instructions and a .bat file now.  when inside dynamo you activate shortcuts by pressing and holding one letter, then pressing another.  your first shortcut is K-S, press and hold K, then press and hold S.  This should bring up the customization shortcuts dialog.
