### ISSUE TITLE
[Improvement] Dont force close after shortcut assigned

### ISSUE THREAD

**Issue by Amoursol** [wynged/DynaFire#4]
It would be super cool if the window doesn't **force close** after setting a single shortcut!

**Comment by wynged** [comment]
I don't think it does... but the use might not be intuitive.  You can assign as many two letter shortcuts as you want, and when you click save settings they are all saved, can you check if that works?

**Comment by Amoursol** [comment]
Yeah... I'm just a moron. I assumed you needed to 'save' to lock them in.

**Comment by wynged** [comment]
You got it now, do you think we need some kind of explaination of this behavior in the UI?

**Comment by Amoursol** [comment]
Could rename to 'Save and Close' ?
